[package]
name = "tansu-broker"
description = "Tansu Kafka API compatible broker"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["dynostore"]
dynostore = ["dep:object_store"]

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
console.workspace = true
futures.workspace = true
glob.workspace = true
http-body-util.workspace = true
humantime.workspace = true
hyper-util.workspace = true
hyper.workspace = true
indicatif.workspace = true
jsonschema.workspace = true
object_store = { workspace = true, optional = true }
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
rama.workspace = true
rand.workspace = true
regex.workspace = true
rsasl.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tansu-auth.workspace = true
tansu-model.workspace = true
tansu-sans-io.workspace = true
tansu-service.workspace = true
tansu-storage.workspace = true
thiserror.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
anyhow.workspace = true
object_store = { workspace = true }
pretty_assertions.workspace = true
tansu-storage = { workspace = true }
