[package]
name = "tansu"
description = "Apache Kafka compatible broker backed by an object store (S3, GCS or memory)"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
dotenv.workspace = true
mimalloc.workspace = true
tansu-broker = { workspace = true, default-features = false, optional = true }
tansu-cli = { workspace = true, default-features = false, optional = true }
tansu-sans-io.workspace = true
tansu-storage = { workspace = true, default-features = false, optional = true }
tansu-topic.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = ["dynostore"]
dynostore = ["dep:tansu-broker", "dep:tansu-cli", "dep:tansu-storage", "tansu-broker/dynostore", "tansu-cli/dynostore", "tansu-storage/dynostore"]
